import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Footer from '@shared-components/Footer';
import Navbar from '@shared-components/Navbar';
import LoadingIndex from '@shared-components/LoadingIndex';
import '@shared/styles/globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Clawbit Labs',
  description: 'Generated by create next app',
};

export default function ErrorLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased 2xl:max-w-450 2xl:mx-auto`}
      >
        <LoadingIndex />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
